config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pictures#index'
  resources :pictures do
    resources :my_lists, only: :create
    resources :memos, only: [:create, :show, :edit, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
    member do
      get 'user'
    end
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :picture
  has_one_attached :image

  validates :offsetX, presence: true
  validates :offsetY, presence: true
end

app/models/my_list.rb
class MyList < ApplicationRecord
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_many :memos, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  has_one_attached :image
  
  validates :text, presence: { message: 'が入力されていません' }
  validates :image, presence: { message: 'が選択されていません' }
  validates :public_private, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true, length: { maximum: 8 }
  has_many :pictures, dependent: :destroy
  has_many :favorites
  has_many :favorite_pictures, through: :favorites, source: :tweet
  has_one_attached :image
  has_many :my_lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile, :image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :profile, :image])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.new(picture_id: params[:picture_id])
    favorite.save
    redirect_to picture_path(params[:picture_id])
  end

  def destroy
    favorite = Favorite.find_by(picture_id: params[:picture_id], user_id: current_user.id)
    favorite.destroy
    redirect_to picture_path(params[:picture_id])
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_picture, except: :create
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def create
    Memo.create(memo_params)
    redirect_to picture_path(id: params[:picture_id])
  end

  def show
    @link = Memo.find(params[:id])
  end

  def edit
    @link = Memo.find(params[:id])
  end

  def update
    link = Memo.find(params[:id])
    link.update_attributes(momo_edit_params)
    redirect_to picture_path(@picture)
  end

  def destroy
    memo = Memo.find(params[:id])
    memo.destroy
    redirect_to picture_path(@picture)
  end

  private

  def memo_params
    params.require(:memo).permit(:info, :image).merge(picture_id: params[:picture_id], offsetX: params[:offsetX], offsetY: params[:offsetY])
  end
  
  def momo_edit_params
    params.require(:memo).permit(:info, :image)
  end

  def set_picture
    @picture = Picture.find(params[:picture_id])
  end

  def move_to_index
    redirect_to root_path unless current_user.id == @picture.user.id
  end
end

app/controllers/my_lists_controller.rb
class MyListsController < ApplicationController
  def create
    @my_list = MyList.new(my_list_params)
    if @my_list.save
      redirect_to picture_path(id: params[:picture_id])
    end
  end

  private
  def my_list_params
    params.require(:my_list).permit(:list_name).merge(user_id: current_user.id)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :user, :search]
  before_action :search_pictures, only: [:index, :create, :user, :search]
  before_action :set_picture, only: [:show, :update, :destroy]
  before_action :move_to_index, only: :destroy

  def index 
    @pictures = Picture.where(public_private: "公開").includes(:user).order('created_at DESC')
    @picture = Picture.new
    @random = ["green-memo.png", "透明背景メモ.png"]
  end

  #def new 
    #@picture = Picture.new
  #end

  def create 
    @pictures = Picture.where(public_private: "公開").includes(:user).order('created_at DESC')
    @picture = Picture.new(picture_params)
    if @picture.save
      redirect_to picture_path(@picture)
    else
      render :index
    end
    
  end

  def show 
    @memo = Memo.new
    @my_list = MyList.new
    @my_lists = current_user.my_lists
    @links = @picture.memos
    if user_signed_in?
      gon.current_user_id = current_user.id
      gon.picture_user_id = @picture.user.id
      gon.user_signed_in = user_signed_in?
    end
  end

  def edit 
  end

  def update
    @picture.update(update_picture)
    redirect_to picture_path(@picture)
  end

  def destroy
    @picture.destroy
    redirect_to root_path
  end

  def user
    @user = User.find(params[:id]) 
    @private_pictures = @user.pictures.where(public_private: "非公開").order('created_at DESC')
    @public_pictures = @user.pictures.where(public_private: "公開").order('created_at DESC')
    @favorites = @user.favorites
  end

  def search
    @results = @p.result.includes(:user).order('created_at DESC')
    @picture = Picture.new
    render :index
  end

  private

  def picture_params
    params.require(:picture).permit(:text, :image, :public_private).merge(user_id: current_user.id)
  end

  def search_pictures
    @p = Picture.ransack(params[:q])
  end

  def update_picture
    params.require(:picture).permit(:public_private)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def move_to_index
    redirect_to root_path unless current_user.id == @picture.user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/my_lists_helper.rb
module MyListsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>PinPic</title>
    <%= include_gon(:init => true) %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>
    

app/views/memos/edit.html.erb
<p class="memo-edit-p">挿入内容の編集</p>
<%= form_with(model: [@picture, @link], class: 'memo-form', id: 'form-field', local: true) do |f| %>
  <div class="form-input">
    <%= f.text_area :info, class: 'form-message', placeholder: 'type a message', size: "50 x 5", maxlength: "150" %>
    <br>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, placeholder: 'Image url' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/memos/show.html.erb
<div class="link-wrapper"> 
  <div class="back-link">
    <%= link_to "戻る", :back %>
  </div>
  <% if user_signed_in? && current_user.id == @picture.user.id %>
  <div class="edit-delete">
  <%= link_to '編集', edit_picture_memo_path(@picture, @link) %>
  <%= button_to '削除', picture_memo_path(@picture, @link), method: :delete, onclick: "return confirm('画像を削除しますか？')" %>
  </div>
  <% end %>
</div>
<div class="memo-show-wrapper">
  <% if @link.image.attached? %>
  <div class="memo-show-picture-container">
    <%= image_tag @link.image, alt: "画像", class: "memo-show-picture" %>
  </div>
  <% end %>
  <div class="description-image">
    <div class="memo-description">
      <%= auto_link(simple_format(@link.info)) %>
    </div>
  </div>
</div>

app/views/pictures/_error_messages.html.erb
<% if model.errors.any? %>
  <div class = "alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/pictures/index.html.erb
<header>
  <div class="header-wrapper" >
    <div class="header-title">
      <a href="/">PinPic</a>
    </div>
    <div class="header-right">
      <div class="free-word">
        <%= search_form_for @p, url: search_pictures_path, class: "free-word-form" do |f| %>
          <%= f.search_field :text_cont, placeholder: 'キーワードから探す', class: "free-word-filed" %>
          <%= f.hidden_field :public_private_eq, value: "公開" %>
          <%= button_tag type: :submit, class: 'search-button' do %>
            <%= image_tag "search.png", class: "search-icon" %>
          <% end %>
        <% end %>
      </div>
      <ul class="session">
      <% if user_signed_in? %>
        <li class="header-list"><%= link_to 'マイページ', user_picture_path(current_user) %></li>
        <li class="header-list"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li class="header-list"><%= link_to 'ログイン', new_user_session_path %></li>
        <li class="header-list"><%= link_to '新規登録', new_user_registration_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</header>
<% b_images = ["透明背景メモ.png", "背景メモ2.png", "背景メモ3.png", "背景メモ4.png", "背景メモ5.png", "背景メモ6.png", "背景メモ7.png", "背景メモ9.png", "背景メモ10.png", "背景メモ11.png"] %>
<div class="current-user-name">
  <% if user_signed_in? %>
    現在のユーザー：<%= current_user.nickname  %>
  <% end %>
</div>
<div class="whole-wrapper">
  <% if user_signed_in? %>
  <div class="side-bar">
    <% if user_signed_in? %>
       <span class="new-post-link">新規投稿</span>
        <div class="post-message">
          ※著作権に違反するような<br>画像の投稿はお控えいただけますようお願いします。
        </div>
        <div class="new-post">
          <%= form_with model: @picture, class: "new-post-form", local: true do |f| %>
          <%= render 'error_messages', model: f.object %>
            <%= label :text, 'タイトル (20文字以内)', class: "post-title" %>
            <br><%= f.text_field :text, class: "text-field", placeholder: 'タイトルを入力してください', maxlength: 20, size: "30" %>
            <label>
            <br><%= f.label :image, '画像', class: "post-image-label" %>
            <br><%= f.file_field :image, class: "post-image-field" ,placeholder: 'Image url'%>
            <br><input name="picture[public_private]" value="非公開" type="hidden">
            <br><%= f.submit '送信', class: "" %>
          <% end %>
        </div>
    <% end %>
  </div>
  <% end %>
  <% if @results.nil? %>
    <div class="contents-wrapper">
      <div class="index-title">
      みんなの投稿一覧
      </div>
      <div class="picture-container">
        <% if @pictures.present? %>
          <% @pictures.each do |picture| %>
            <div class="index-contents" style='background-image: url("/images/background/<%= b_images.sample %>");-moz-background-size:100% 100%;
            background-size:100% 100%;'>
              <div class="picture-wrapper">
                <%= link_to image_tag(picture.image , width: '80%', height: '100%', alt: "画像"), picture_path(picture), class: "picture" %>
              </div>
              <div class="description">
                <div class="title">
                  <p><%= picture.text.truncate(10) %></p>
                </div>
                <div class="user-name">
                  <%= link_to "投稿者: #{picture.user.nickname}", user_picture_path(picture.user.id) %>
                </div>
                <div class="favorite-count">
                  <div class="icon">
                    <%= image_tag 'heart-icon', class: "heart-icon" %>
                    <%= picture.favorites.count %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="contents-wrapper">
      <div class="index-title">
      検索結果一覧
      </div>
      <div class="picture-container">
        <% if @results.present? %>
          <% @results.each do |result| %>
            <div class="index-contents" style='background-image: url("/images/background/<%= b_images.sample %>");-moz-background-size:100% 100%;
            background-size:100% 100%;'>
              <div class="picture-wrapper">
                <%= link_to image_tag(result.image , width: '80%', height: '100%', alt: "画像"), picture_path(result), class: "picture" %>
              </div>
              <div class="description">
                <div class="title">
                  <p><%= result.text.truncate(10) %></p>
                </div>
                <div class="user-name">
                  <%= link_to "投稿者: #{result.user.nickname}", user_picture_path(result.user.id) %>
                </div>
                <div class="favorite-count">
                  <div class="icon">
                    <%= image_tag 'heart-icon', class: "heart-icon" %>
                    <%= result.favorites.count %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pictures/new.html.erb
<div class="new-post-wrapper">
  <div class="new-post-container">
    <div class="new-post-title">
      <h1>新規投稿</h1>
      <p>※著作権に違反するような画像の投稿は<br>お控えいただけますようお願いします。</p>
    </div>
    <div class="new-post-form">
      <%= form_with model: @picture, class: "new-post-filed", local: true do |f| %>
      <%= render 'error_messages', model: f.object %>
        <%= label :text, 'タイトル', class: "title-label" %>
        <br><%= f.text_field :text, class: "new-post-text", placeholder: '20文字以内でタイトルを入力してください', maxlength: 20 %>
        <label>
        <br><%= f.label :image, '画像', class: "image-label" %>
        <br><%= f.file_field :image, class: "new-post-image" ,placeholder: 'Image url' %>
        <br><input name="picture[public_private]" value="非公開" type="hidden">
        <br><%= f.submit '送信', class: "new-post-submit" %>
        <br><%= link_to 'トップページへ戻る', root_path, class: "to-top-page" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pictures/search.html.erb
<header>
  <div class="header-wrapper">
    <div class="header-title">
      <a href="/">PinZD</a>
    </div>
    <div class="header-right">
      <div class="free-word">
        <%= search_form_for @p, url: search_pictures_path, class: "free-word-form" do |f| %>
          <%= f.search_field :text_cont, placeholder: 'キーワードから探す', class: "free-word-filed" %>
          <%= f.hidden_field :public_private_eq, value: "公開" %>
          <%= button_tag type: :submit, class: 'search-button' do %>
            <%= image_tag "search.png", class: "search-icon" %>
          <% end %>
        <% end %>
      </div>
      <ul class="session">
      <% if user_signed_in? %>
        <li><%= link_to 'マイページ', user_picture_path(current_user) %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
        <li><%= link_to '新規登録', new_user_registration_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</header>
<div class="whole-wrapper">
  <div class="side-bar">
    
  </div>
  <div class="result-wrapper">
    <div class="index-title">
      検索結果一覧
    </div>
    <div class="picture-container">
      <% unless @results.empty? %>
        <% @results.each do |result| %>
          <div class="contents">
            <div class="picture-wrapper">
              <%= link_to image_tag(result.image , width: '100%', height: '100%', alt: "画像"), picture_path(result), class: "picture" %>
              <%= image_tag 'picture-pin2.png', class: "picture-pin" %>
            </div>
            <div class="description">
              <div class="title">
                <p><%= result.text %></p>
              </div>
              <div class="user-name">
                <%= link_to "投稿者: #{result.user.nickname}", user_picture_path(result.user.id) %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/pictures/show.html.erb
<header class="show-header">
  <div class="header-wrapper">
    <div class="header-title">
      <a href="/">PinPic</a>
    </div>
    <div class="header-right">
      <ul class="session">
      <% if user_signed_in? %>
        <li class="header-list"><%= link_to 'マイページ', user_picture_path(current_user) %></li>
        <li class="header-list" id="my-list">マイリストへ追加
          <div class="my-list hidden" id="pull-down">
            <% if @my_lists.present? %>
              <% @my_lists.each do |my_list| %>
                <div class="pull-down-list"><%=  my_list.list_name %></div>
              <% end %>
            <% end %>
            <%= form_with model: [@picture, @my_list], class: 'my-list-form', local: true do |f| %>
              <%= f.text_field :list_name, class: "my-list-field" %>
              <%= f.submit '新規リスト作成' %>        
            <% end %>
          </div>
        </li>
        <li class="header-list"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
        <li><%= link_to '新規登録', new_user_registration_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</header>
<div class="status-form">
  <% if user_signed_in? && current_user.id == @picture.user.id %>
    <%= form_with model: @picture, class: "change-status", local: true do |f| %>
    ・ステータス: <%= f.radio_button :public_private, "公開" %>公開<%= f.radio_button :public_private, "非公開" %>非公開
    <%= f.submit '変更' %>
    <% end %>
    <%= button_to '画像を削除する', picture_path(@picture), method: :delete, class: "destroy-link", onclick: "return confirm('画像を削除しますか？')" %>
  <% end %>
</div>
<div class="show-wrapper">
  <div class="picture-form-wrapper">
    <div class="title-picture-wrapper">
      <div class="sub-contents">
        <div> </div>
        <div class="picture-title">
          <p><%= @picture.text %></p>
        </div>
        <div class="favorite-memo-switch">
          <% if user_signed_in? %>
            <% if @picture.favorited_by?(current_user) %>
              <%= button_to 'お気に入りを解除する', picture_favorites_path(@picture.id), method: :delete, class: "favorite-change" %>
            <% else %>
              <%= button_to 'お気に入りへ登録する', picture_favorites_path(@picture.id), method: :post, class: "favorite-change" %>
            <% end %>
          <% end %>
          <input id='memo-switch' type="button" value="ふきだしを表示">
        </div>
      </div>
      <div class="show-picture" id="position">
        <img src="<%= url_for(@picture.image) %>" alt="画像" class="main-picture" id="picture" >
        <% if @links.present? %>
          <% @links.each do |link| %>
            <a class="marker" href="/pictures/<%= link.picture.id %>/memos/<%= link.id %>" style="position: absolute;
              top: <%= link.offsetY %>%;
              left: <%= link.offsetX %>%;
              transform: translate(-25%, -80%);" id="<%= link.id %>">
              <%= image_tag "picture-pin.png", class: "pin" %>
            </a>
            <% if link.info.present? || link.image.attached? %>
              <span class="memo-info" id="memo<%= link.id %>" style="position: absolute;
                top: <%= link.offsetY  %>%;
                left: <%= link.offsetX  %>%;"
                >
                <% if link.image.attached? %>
                  <a href="/pictures/<%= link.picture.id %>/memos/<%= link.id %>"><%= image_tag link.image, alt: "画像", class: "memo-picture" %></a><br>
                <% end %>
                <%= auto_link(simple_format(link.info)) %>
              </span>
            <% end %>
          <% end %> 
        <% end %>
      </div>
    </div>
    <div class="form-wrapper">
      <%= form_with(model: [@picture, @memo], class: 'memo-form hidden', id: 'form-field', local: true) do |f| %>
        <div class="form-input">
          <%= f.text_area :info, class: 'form-message', placeholder: 'maxlength 150', size: "40 x 5", maxlength: "150"%><br>
          <label class="form-image">
            <span class="image-file">画像</span><br>
            <%= f.file_field :image, placeholder: 'Image url', class: "memo-form-image" %>
          </label>
        </div>
        <%= f.submit '送信', class: 'form-submit' %>
      <% end %>
    </div>
  </div>
</div>

app/views/pictures/user.html.erb
<header>
  <div class="header-wrapper">
    <div class="header-title">
      <a href="/">PinPic</a>
    </div>
    <div class="header-right">
      <ul class="session">
      <% if user_signed_in? && current_user.id == @user.id %>
        <li class="header-list"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% elsif user_signed_in? %>
        <li class="header-list"><%= link_to 'マイページ', user_picture_path(current_user) %></li>
        <li class="header-list"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li class="header-list"><%= link_to 'ログイン', new_user_session_path %></li>
        <li class="header-list"><%= link_to '新規登録', new_user_registration_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</header>
<div class="user-profile">
  <div class="profile-container">
    <div class="user-image-name">
      <% if @user.image.attached? %>
        <%= image_tag @user.image, class: "profile-image"%>
      <% else %>
        画像が設定されていません
      <% end %>
      <div><%= @user.nickname %></div>
      <div>
        <% if user_signed_in? && current_user.id == @user.id %>
          <%= link_to 'プロフィールを編集する',edit_user_registration_path %>
        <% end %>
      </div>
    </div>
    <% if @user.profile.present? %>
      <%= @user.profile %>
    <% else %>
      プロフィールが設定されていません
    <% end %>
  </div>
</div>
<div class="user-page-wrapper">
  <div class="user-main" id="public-main">
    <% if user_signed_in? && current_user.id == @user.id %>
      <div class="sub-title">
        <h1>公開画像一覧</h1>
      </div>
    <% else %>
      <div class="sub-title2">
        <h1><%= @user.nickname %>さんの投稿画像一覧</h1>
      </div>
    <% end %>
    <div class="user-picture-container">
      <% if @public_pictures.present? %>
        <% @public_pictures.each do |public_picture| %>
          <div class="user-contents">
            <div class="picture-wrapper">
              <%= link_to image_tag(public_picture.image , width: '80%', height: '100%', alt: "画像"), picture_path(public_picture), class: "picture" %>
            </div>
            <div class="description">
              <div class="title">
                <p class="title"><%= public_picture.text.truncate(10) %></p>
              </div>
              <div class="favorite-count">
                <div class="icon">
                  <%= image_tag 'heart-icon', class: "heart-icon" %>
                  <%= public_picture.favorites.count %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="user-main" id="private-main" style="display: none;">
    <div class="sub-title">
      <h1>非公開画像一覧</h1>
    </div>
    <div class="user-picture-container">
      <% if @private_pictures.present? %>
        <% @private_pictures.each do |private_picture| %>
          <div class="user-contents">
            <div class="picture-wrapper">
              <%= link_to image_tag(private_picture.image , width: '80%', height: '100%', alt: "画像"), picture_path(private_picture), class: "picture" %>
              <%#= image_tag 'picture-pin2.png', class: "picture-pin" %>
            </div>
            <div class="description">
              <div class="title">
                <p class="title"><%= private_picture.text.truncate(10) %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="user-main" id="favorite-main" style="display:none;">
      <div class="sub-title">
        <h1>お気に入り一覧</h1>
      </div>
    <div class="user-picture-container">
      <% if @favorites.present? %>
        <% @favorites.each do |favorite| %>
          <div class="user-contents">
            <div class="picture-wrapper">
              <%= link_to image_tag(favorite.picture.image , width: '80%', height: '100%', alt: "画像"), picture_path(favorite.picture), class: "picture" %>
            </div>
            <div class="description">
              <div class="title">
                <p class="title"><%= favorite.picture.text.truncate(10) %></p>
              </div>
              <div class="user-name">
                <%= link_to "投稿者: #{favorite.picture.user.nickname}", user_picture_path(favorite.picture.user.id) %>
              </div>
              <div class="favorite-count">
                <div class="icon">
                  <%= image_tag 'heart-icon', class: "heart-icon" %>
                  <%= favorite.picture.favorites.count %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="menu-bar">
  <% if user_signed_in? && current_user.id == @user.id %>
    <input id='status-change' type="button" value="非公開画像を表示"><br>
    <input id='favorite-button' type="button" value="お気に入りを表示"><br>
  <% end %>
  </div>
</div>